const routes = {
  ROOT: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_NEXTSTEP: '/forgot-password-nextstep',
  DASHBOARD: '/dashboard',
  TRANSACTIONS: '/transactions',
  PAY_CONFIG: '/pay-config',
  PAY_STATUS: '/pay-status',
  BULK: '/bulk',
  SINGLE: '/single',
  CREATE_BANK: '/create-bank',
  LIST_BANKS: '/list-banks',
  CREATE_MERCHANT: '/create-merchant',
  LIST_MERCHANTS: '/list-merchants',
  BUSINESSES: '/businesses',
  CREATE_USRE: '/create-user',
  LIST_USRES: '/list-users',
  NOTIFICATIONS: '/notifications',
  REPORT: '/report',
  LOGS: '/logs',
  PROFILE: '/profile',
  TRANSACTIONS_DETAIL: '/transaction_deatil',
  IMPORTED_BULK: '/imported_bulk',
  REFUNDS: '/refunds',
  CREATE_BRANCH: '/create-branch',
  LIST_BRANCHES: '/list-branches',
  DOCUMENTATION: '/documentation',
  SETTINGS: '/settings',
  VISA_MASTERCARD: '/visa-mastercard',
  BRANCH_BULK: '/branch-bulk',
  REQUEST_REFUND: '/request-refund',
};

export default routes;
