const ActionType = {
  /*  MICRO-SERVICE  */
  GET_AUTH_SERVICE: 'GET_AUTH_SERVICE',
  GET_AUTH_SERVICE_SUCCESS: 'GET_AUTH_SERVICE_SUCCESS',
  GET_AUTH_SERVICE_FAIL: 'GET_AUTH_SERVICE_FAIL',


  /*  AUTH  */
  LOGIN_LOAD: 'LOGIN_LOAD',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
};

export default ActionType;